### ISSUE TITLE
Menu Sounds not playing

### ISSUE THREAD

**Issue by ghost** [libretro/LudOS#10]
CPU: Intel Haswell Intel© Core™ i5-4670 CPU @ 3.40GHz × 4
GPU: N/A
RAM: 4gb

LudOS: Genricx86_64 1.0 Alpha30

There are several issues I had found so far starting with Menu not playing sounds.

**Comment by kivutar** [comment]
I can't reproduce on my Macbook Air with Generic x86_64 Alpha32

**Comment by kivutar** [comment]
Sorry, I have no way to reproduce this. It has been working fine on all my laptops so far.
