### ISSUE TITLE
Logitech F310 Controller Configuration

### ISSUE THREAD

**Issue by ghost** [libretro/LudOS#11]
CPU: Intel Haswell Intel© Core™ i5-4670 CPU @ 3.40GHz × 4
GPU: N/A
RAM: 4gb

LudOS: Genricx86_64 1.0 Alpha30

LudOS recognizes my Logitech F310 controller but does not allow me to configure it. Please add auto-configure to it in the future this controller is one of the best I have used when it comes to emulation. 

When I had a Raspberry Pi 3 I noticed some other controllers required more power to use and ends up putting the RPi3 in the under voltage state. Which made it necessary to either get a power source with more amperage to supply the RPi3 or use a less demanding controller. That happened when trying to put a second controller to get some multiplayer going.

**Comment by kivutar** [comment]
This pad isn't supported because I don't own it
