### ISSUE TITLE
PS1 / PSx CCD formats not recognized

### ISSUE THREAD

**Issue by ghost** [libretro/LudOS#12]
CPU: Intel Haswell Intel© Core™ i5-4670 CPU @ 3.40GHz × 4
GPU: N/A
RAM: 4gb

LudOS: Genricx86_64 1.0 Alpha30

Scanning PSx games that are in the ccd format are not being added to the playlist.

**Comment by kivutar** [comment]
Hi, sorry but we can only support formats supported by the emulators included.
Use bin+cue instead.
