### ISSUE TITLE
Atari Lynx Playlist / Scanning

### ISSUE THREAD

**Issue by ghost** [libretro/LudOS#15]
CPU: Intel Haswell Intel© Core™ i5-4670 CPU @ 3.40GHz × 4
GPU: N/A
RAM: 4gb

LudOS: Genricx86_64 1.0 Alpha30

Atari Lynx roms are also not being added when scanned to the playlist. Those are unzipped roms as well.

**Comment by kivutar** [comment]
I'm trying to reproduce on Ludo v0.11.2. and I was able to scan an unzipped .lnx game.

**Comment by kivutar** [comment]
Should be fixed by now
