### ISSUE TITLE
Gamepad issue on Raspberry pi 4

### ISSUE THREAD

**Issue by ghost** [libretro/LudOS#18]
Raspberry Pi 4 B 

LudOS version: 1 alpha 30

Ive tested the following gamepads: Xbox 360, Xbox One S, Xbox One (firmware 2015) and the Logitech F310 controller

Non would let me navigate or use it on LudOS out the box, the only one that does is the xbox 360 gamepad after a game is selected. I have to select a game through my keyboard then be able to play the game with that xbox 360 controller.

**Comment by kivutar** [comment]
Thanks for the report.

I tested my Xbox One pad now and it was working.

I will try more pads.

**Comment by ghost** [comment]
> Thanks for the report.
> 
> I tested my Xbox One pad now and it was working.
> 
> I will try more pads.

How can I add and contribute my gamepads for Ludo/ Ludo OS? I don't see a folder for gamepads for Ludo.

**Comment by kivutar** [comment]
They are directly in the source code

**Comment by kivutar** [comment]
We now switched to GLFW gamepad db, this should be fixed.
