### ISSUE TITLE
Find a way to set OpenGL 2.1 only on RPi

### ISSUE THREAD

**Issue by kivutar** [libretro/LudOS#2]
This change should be on RPi only, not on Generic https://github.com/libretro/LudOS/pull/1/files#diff-0b4bcf58d0c569b8e6c5731053aa342cR13

**Comment by natinusala** [comment]
I see two solutions:

1. Override the service in the RPi project (not good)
2. have a file like  `/etc/ludo.args` (or whatever) and inside put platform specific args - have Ludo read it with `/usr/bin/ludo --args /etc/ludo.args`, and finally put the file in `projects/<platform>/filesystem/etc/ludo.args`, so for RPi that would be `projects/RPi/filesystem/etc/ludo.args` containing `-glver=21`

**Comment by kivutar** [comment]
I see, not a bad idea. I would use the `/etc/ludo.json` for this, and have a setting there to set the OpenGL version. I wouldn't expose this setting in the UI. And that would do the trick.
