### ISSUE TITLE
Find a way to enable xorg-configure@modesetting.service on RPi only

### ISSUE THREAD

**Issue by kivutar** [libretro/LudOS#3]
This should happen only on RPi https://github.com/libretro/LudOS/pull/1/files#diff-80e646d150bcc2f1cb85686bfeb34029R6

I have tried to add a `enable_service xorg-configure@modesetting.service` wrapped in a conditional in the `post_install` hook of `packages/x11/xserver/xorg-server/package.mk` but it didn't work.

Maybe because `xorg-configure@modesetting.service`  lacks an `[Install]` section?

**Comment by natinusala** [comment]
Why don't you put it in the RPi project metapackage ? That would be the `packages/ludos/RPi` package

**Comment by kivutar** [comment]
You mean the OEM package? And replicating the whole `xorg-server` package in there as a way to override?

**Comment by kivutar** [comment]
For some reasons, doing a `enable_service xorg-configure@modesetting.service`fails. It is not enough to create the symlink that shows that the service is enabled.
Maybe because there are no `[Install]` section there.
I've noticed this by inspecting the content of the build dir.

**Comment by natinusala** [comment]
This is related to #4 - the udev rule is supposed to start the service. So, when _enabled_ alone it will not start until the udev rule is triggered. Doing `Requires=` manually makes it start no matter what.

**Comment by kivutar** [comment]
This did the trick. Thanks!
